/**
 * registry.js — the multi-tenant store registry.
 *
 * Each entry is one Shopify store the concierge serves. ALL per-store settings live here;
 * per-store DATA (catalogue + theme tokens) lives in ./<id>/ and is generated by the scripts.
 *
 * To onboard a new store:
 *   1. Add an entry below (id, storeUrl, brand voice, prompts, allowedOrigins).
 *   2. npm run fetch -- <id>          (writes stores/<id>/catalogue.json)
 *   3. npm run extract-theme -- <id>  (writes stores/<id>/theme-tokens.{json,css})
 *   4. Add ANTHROPIC_API_KEY_<ID> in your host's env (per-store usage tracking).
 *   5. Add the embed snippet with data-store="<id>" to that store's theme.liquid.
 *
 * Per-store API key resolution (see src/recommender.js):
 *   env `apiKeyEnv` override  ->  `ANTHROPIC_API_KEY_<ID>`  ->  `ANTHROPIC_API_KEY` (fallback)
 */

const STORES = {
  enrgy: {
    id: 'enrgy',
    storeName: 'ENRGY Clothing',
    // Use the www version — confirmed working for products.json and cart permalinks.
    storeUrl: 'https://www.enrgyclothing.com',
    currency: 'EUR',
    currencySymbol: '€',
    // 'gift-concierge' (adapted for apparel: shop-the-look) or 'spec-advisor'.
    mode: 'gift-concierge',
    brandVoice:
      'young, energetic and street — a confident Irish gymwear/streetwear brand that talks ' +
      'like its customer, hyped about new "drops", never corporate or stiff.',
    examplePrompts: [
      'Build me a full Stealth fit in arctic blue',
      'A gift for a 16-year-old into streetwear, ~€40',
      'Something to train in under €25',
    ],
    // Origins allowed to call the API and run the same-origin AJAX cart (the storefront domains).
    allowedOrigins: ['https://www.enrgyclothing.com', 'https://enrgyclothing.com'],
    // Optional: override the per-store API key env var name. Defaults to ANTHROPIC_API_KEY_ENRGY.
    // apiKeyEnv: 'ANTHROPIC_API_KEY_ENRGY',
  },
};

function getStore(id) {
  return STORES[id] || null;
}

function allStores() {
  return Object.values(STORES);
}

/** Env var name holding this store's Anthropic key. */
function apiKeyEnvName(store) {
  if (store.apiKeyEnv) return store.apiKeyEnv;
  const slug = String(store.id).toUpperCase().replace(/[^A-Z0-9]+/g, '_');
  return `ANTHROPIC_API_KEY_${slug}`;
}

/** Every origin allowed across all stores (for the CORS allow-list). */
function allAllowedOrigins() {
  const set = new Set();
  for (const s of allStores()) (s.allowedOrigins || []).forEach((o) => set.add(o));
  return [...set];
}

module.exports = { STORES, getStore, allStores, apiKeyEnvName, allAllowedOrigins };
